# Development Docker Compose - MongoDB only
# For full application deployment, use: docker-compose -f docker-compose.full.yml up

services:
  mongodb:
    image: mongo:7.0
    container_name: synaptik-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: synaptik
    volumes:
      - mongodb_data:/data/db
    networks:
      - synaptik-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: synaptik-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - synaptik-network

volumes:
  mongodb_data:

networks:
  synaptik-network:
    driver: bridge
