services:
  # MongoDB Database (same as production)
  mongodb:
    image: mongo:7.0
    container_name: synaptik-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: synaptik
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - synaptik-dev-network

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:1.0.0
    container_name: synaptik-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - synaptik-dev-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  synaptik-dev-network:
    driver: bridge