name: synaptik-mcp

services:
  # MCP Server for AI Integration
  mcp-server:
    build:
      context: ../mcp-server
      dockerfile: Dockerfile
    container_name: synaptik-mcp-server
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      SYNAPTIK_API_URL: http://localhost:8080/api
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: synaptik-network
    external: true