name: synaptik-client

services:
  # React Frontend
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: synaptik-client
    restart: unless-stopped
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: synaptik-network
    external: true