name: Branch Protection

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]
  
# More aggressive concurrency for PR checks
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  JAVA_VERSION: '21'

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.set-outputs.outputs.frontend-changed }}
      backend-changed: ${{ steps.set-outputs.outputs.backend-changed }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper diff analysis

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'client/**'
              - '*.json'
              - '*.yml'
              - '*.yaml'
            backend:
              - 'server/**'
              - '*.gradle*'
              - 'gradle/**'

      - name: Set outputs
        id: set-outputs
        run: |
          echo "frontend-changed=${{ steps.changes.outputs.frontend }}" >> $GITHUB_OUTPUT
          echo "backend-changed=${{ steps.changes.outputs.backend }}" >> $GITHUB_OUTPUT

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        continue-on-error: true

  frontend-lint-only:
    needs: fast-checks
    if: needs.fast-checks.outputs.frontend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: |
          cd client
          npm ci --prefer-offline --no-audit

      - name: Fast lint check
        run: |
          cd client
          npm run lint -- --max-warnings 0

      - name: Type check
        run: |
          cd client
          npm run type-check

  backend-compile-only:
    needs: fast-checks
    if: needs.fast-checks.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true  # Read-only for PR checks

      - name: Fast compile check
        run: |
          cd server
          chmod +x gradlew
          ./gradlew compileJava compileTestJava --no-daemon

  security-quick-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

  status-summary:
    runs-on: ubuntu-latest
    needs: [fast-checks, frontend-lint-only, backend-compile-only, security-quick-scan]
    if: always()
    
    steps:
      - name: PR Check Summary
        run: |
          echo "## 🚀 PR Quick Checks Summary" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.frontend-lint-only.result }}" = "success" ] || [ "${{ needs.fast-checks.outputs.frontend-changed }}" = "false" ]; then
            echo "✅ Frontend checks passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Frontend checks failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.backend-compile-only.result }}" = "success" ] || [ "${{ needs.fast-checks.outputs.backend-changed }}" = "false" ]; then
            echo "✅ Backend checks passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Backend checks failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.security-quick-scan.result }}" = "success" ]; then
            echo "✅ Security scan passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Security scan found issues" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "💡 **Note:** Full CI tests will run on the target branch" >> $GITHUB_STEP_SUMMARY
