name: Docker Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: roudranil/synaptik

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          
          # Validate semantic version format
          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format: $VERSION"
            exit 1
          fi
          
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f1-2)
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          
          echo "🏷️ Building version: $VERSION"
          echo "📦 Tags: $VERSION, $MINOR, $MAJOR, latest"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.minor }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.major }}
            ${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.title=Synaptik
            org.opencontainers.image.description=A next-generation task management application with TaskWarrior DNA
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          body: |
            ## 🐳 Docker Images
            
            This release is available on Docker Hub with the following tags:
            
            - `roudranil/synaptik:${{ steps.version.outputs.version }}` - Exact version
            - `roudranil/synaptik:${{ steps.version.outputs.minor }}` - Latest patch of minor version
            - `roudranil/synaptik:${{ steps.version.outputs.major }}` - Latest minor of major version
            - `roudranil/synaptik:latest` - Latest stable release
            
            ## 🚀 Quick Start
            
            ```bash
            # Using exact version (recommended for production)
            docker run -p 8080:8080 roudranil/synaptik:${{ steps.version.outputs.version }}
            
            # Using docker-compose
            curl -sSL https://raw.githubusercontent.com/Dukeroyahl/synaptik/main/dist/docker-compose.yml -o docker-compose.yml
            docker-compose up -d
            ```
            
            ## 📖 Documentation
            
            - [User Guide](https://github.com/Dukeroyahl/synaptik/blob/main/docs/WIKI.md#user-guide)
            - [Docker Usage](https://github.com/Dukeroyahl/synaptik/blob/main/docs/WIKI.md#docker-usage)
            - [API Documentation](http://localhost:8080/q/swagger-ui) (after starting)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
