name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'client/**'
      - 'dist/docker/Dockerfile.frontend'
      - 'dist/docker/nginx.conf'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'dist/docker/Dockerfile.frontend'
      - 'dist/docker/nginx.conf'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if no changes detected'
        required: false
        default: 'false'
        type: boolean
      version_tag:
        description: 'Custom version tag (e.g., v1.2.3)'
        required: false
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: roudranil/synaptik-frontend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd client
        npm ci

    - name: Build frontend
      run: |
        cd client
        npm run build

    - name: Test frontend
      run: |
        cd client
        npm test -- --passWithNoTests

    - name: Lint frontend
      run: |
        cd client
        npm run lint || true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dist/docker/Dockerfile.frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.IMAGE_NAME }}
        short-description: "Synaptik Frontend - React-based UI for task management and productivity"